# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    container_name: Bakery2mysql
    hostname: Bakery2mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: Bakery2adminer
    hostname: Bakery2adminer
    restart: unless-stopped
    ports:
      - 8069:8080
